### PR TITLE
Support union types for zod generator

### LINKED ISSUE #181: withObjectType option don't support union type
I have gql file like this

```gql
type WorkDivision {
  id: ID!
  name: String!
}

type AttendanceNotEnteredOrDayOff {
  id: ID!
  name: String!
  symbol: String!
}

union AttendanceType = WorkDivision | AttendanceNotEnteredOrDayOff

type Attendance {
  date: String!
  type: AttendanceType!
}

```

**current output**

```ts
export function AttendanceSchema(): z.ZodObject<Properties<Attendance>> {
  return z.object({
    __typename: z.literal('Attendance').optional(),
    date: z.string().min(1),
    type: definedNonNullAnySchema // wrong !
  })
}
```

**expected output**

```ts
export function AttendanceTypeSchema(): z.ZodUnion<[z.ZodObject<Required<Properties<WorkDivision>>>, z.ZodObject<Required<Properties<AttendanceNotEnteredOrDayOff>>>]> {
  return z.union([WorkDivisionSchema(), AttendanceNotEnteredOrDayOffSchema()])
}

export function AttendanceSchema(): z.ZodObject<Properties<Attendance>> {
  return z.object({
    __typename: z.literal('Attendance').optional(),
    date: z.string().min(1),
    type: AttendanceTypeSchema()
  })
}
```

### LINKED ISSUE #236: zod schema generator does not recognize union types
It seems like the implementation does not recognize the `union` types when enabling `withObjectType` option.

I get `unhandled scalar name` error.

Seems like we should add a condition to handle unions here:
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/2a61ef2e07b0c19c52e752a93eeead0c0b95f0b8/src/zod/index.ts#L172

### PR DESCRIPTION
**Pull request by alisabzevari**
Fixes #236 
Fixes #181 

This PR adds support for union types for generating zod schemas when `withObjectType` is enabled.

### CODE REVIEW

**Comment by Code-Hex** [comment]
@alisabzevari Thanks!
Could you add code also yup and myzod?

**Comment by Code-Hex** [comment]
@alisabzevari I believe you can use mixin for yup

**Comment by alisabzevari** [comment]
> I believe you can use mixed and oneof for yup

I tried that but the generated schema cannot properly validate the object.

**Comment by Code-Hex** [comment]
@alisabzevari Could you add this code for yup?


```ts
export function union<T>(
	...schemas: ReadonlyArray<yup.SchemaOf<T>>
): yup.BaseSchema<T> {
  return yup.mixed().test({
    test: (value) => schemas.some((schema) => schema.isValidSync(value))
  })
}
```

And fix yup generator to generate code like below

```ts
function ShapeSchema(): yup.BaseSchema<Shape> {
  return union<Shape>(SquareSchema(), CircleSchema())
}
```

**Comment by alisabzevari** [comment]
I have added the code you mentioned. Please have a look.

**Comment by Code-Hex** [comment]
@alisabzevari Could you please fix the test?

**Review by Code-Hex — APPROVED** [review]
Thanks!

**Pull request merged**
