### PR TITLE
fix: argstype do not get configured prefix, suffix

### PR DESCRIPTION
**Pull request by sschneider-ihre-pvs**
fixes: #499

### CODE REVIEW

**Comment by hinogi** [comment]
@Code-Hex can you check on this please?

**Comment by Code-Hex** [comment]
@hinogi Thanks! Could you add test for this PR?

**Comment by Code-Hex** [comment]
maybe I'd like to think that adding configs for useTypesPrefix and useTypesSuffix is better than this PR.
How about you?

**Comment by hinogi** [comment]
well there are already but they have been overwritten

**Comment by hinogi** [comment]
ok for name they are missing sure would make sense to add them there

**Comment by Code-Hex** [comment]
@sschneider-ihre-pvs Thanks!

**Pull request merged**
