### PR TITLE
add `useTypeImports` config

### LINKED ISSUE #376: Add option "useTypeImports"
This is a feature request. Please add the option `useTypeImports` so we can use it in isomorphic application. 

It should me similar to this option: https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations#usetypeimports

### PR DESCRIPTION
**Pull request by Toanzzz**
Resolve #376

### CODE REVIEW

**Comment by Code-Hex** [comment]
@Toanzzz Thanks for your contribution and suggestion!

Could you fix also yup and zod? (Not only myzod)

And please write test. So I can check your PR!

**Comment by Toanzzz** [comment]
@Code-Hex  Thanks for the reminder, I was quite in rush, sorry 😅

Updated & tested!

**Comment by Code-Hex** [comment]
@Toanzzz Could you please run `yarn prettier` on your local 🙏

**Comment by Toanzzz** [comment]
> @Toanzzz Could you please run `yarn prettier` on your local 🙏

It's done (I didn't know it was so strict)

**Review by Code-Hex — APPROVED** [review]
Thanks!

**Pull request merged**
