### PR TITLE
fix(enum): propagate namingConvention.transformUnderscore to convertNameParts

### PR DESCRIPTION
**Pull request by sutt0n**
When I introduced `useEnumTypeAsDefaultValue` via #640, I failed to propagate this prop down and this resulted in no control over underscores.

Docs are also updated.

### CODE REVIEW

**Comment by sutt0n** [comment]
@Code-Hex I believe that job is failing since the action is running against my fork, and not your repository; thus the ref to `fix/name-parts` doesn't exist.

**Comment by KamalAman** [comment]
+1 this PR, I just ran into these issues

**Comment by sutt0n** [comment]
@Code-Hex This is ready for your review at your convenience. 🙏

**Comment by sutt0n** [comment]
@Code-Hex Howdy, apologies for the double ping -- hope all is well with you! Just wanting to be sure to bump this, as others are having this same issue.

**Review by Code-Hex — APPROVED** [review]
@sutt0n I'm sorry for delay response.
LGTM but Could you fix eslint?

**Comment by Code-Hex** [comment]
I can handle it 🙏

**Pull request merged**
